export { default as StockItem_1 } from 'public/images/stock/1.jpg'
export { default as StockItem_2 } from 'public/images/stock/2.webp'
export { default as StockItem_3 } from 'public/images/stock/3.jpg'
export { default as StockItem_4 } from 'public/images/stock/4.jpg'
export { default as StockItem_5 } from 'public/images/stock/5.jpg'
export { default as StockItem_6 } from 'public/images/stock/6.jpg'
