name: Deploy Site
on:
  push:
    branches: [ main ]
jobs:
  deploy:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 17.x ]

      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3

        - name: Starting Node JS ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: Cache settings
          uses: actions/cache@v3
          with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

        - name: 🔨 Build Project
          run: |
            npm install
            npm run build

        - name: 📂 Deploy to FTP
          uses: SamKirkland/FTP-Deploy-Action@4.3.3
          with:
            server: s4.open.by
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: /repositories/agro-sem-fond/